---
title: "How to Call R in Python"
author: "Wilson Tang"
format:
  revealjs:
    theme: solarized
    transition: fade
    slide-number: true
---

## Slide 1: Why we want R 

- Statistical functions and hypothesis testing can easily be done with built-in
functions
- Exploratory data analysis is more natural with tidyverse
- Data visualization ggplot2 is better than plotnine

---

## Slide 2: Why we want Python

- Data processing is more efficient with pandas; bigger data with Dask or
PySpark
- Automate daily and repetitive tasks with scripts and pipelines
- Preferred for machine learning and AI. Packages like scikit-learn for machine
learning, and PyTorch or TensorFlow for deep learning/ neural networks

---

## Slide 3: Example workflow

<div style="font-size: 20px;">
Raw data 

    |
    ▼ 

Python: Data reading, cleaning and preprocessing


    |
    ▼ 

R: Exploratory data analysis to know our data better

    |
    ▼ 

Python: Feature engineer based on what know about our data and what we need

    |
    ▼ 

R: Statistical analysis and visualization

    |
    ▼ 

Python: Machine learning and deployment
</div>

---

## Slide 4: Data reading, cleaning and preprocessing

```python
import pandas as pd
import numpy as np

file_path = '../ids-f25/data/nyc_crashes_lbdwk_2025.csv'

df = pd.read_csv(file_path,
                 dtype={'LATITUDE': np.float32,
                        'LONGITUDE': np.float32,
                        'ZIP CODE': str})

# column name cleaning
df.columns = df.columns.str.lower().str.replace(' ', '_')

# remove September 7th
df = df[df["crash_date"] != "09/07/2025"].copy()

# handling missing values
df.loc[(df['latitude'] == 0) | (df['latitude'].isna()), 'latitude'] = pd.NA
df.loc[(df['longitude'] == 0) | (df['longitude'].isna()), 'longitude'] = pd.NA

# just read the feather file for simplicity
df = pd.read_feather("../ids-f25/data/nyc_crashes_cleaned.feather")
```

```{python}
import pandas as pd
import numpy as np

df = pd.read_feather("../ids-f25/data/nyc_crashes_cleaned.feather")
```

---

